version: "3"

services:

  chrome:
    image: selenium/standalone-chrome
    hostname: chrome
    ports:
      - 4444:4444

  application:
    build: ./
    depends_on:
      - chrome
    environment:
      - INPUT_FILE=dat/inputs.csv
      - OUTPUT_FILE=dat/outputs.csv
      - REMOTE_HOST=http://chrome:4444
      - VOLUME_PATH=/opt/dat
    volumes:
      - ./:/opt/dat